#!/bin/bash
set -e

# Build the site with production config.

# ./tasks/jekyll --config _config_production.yml
jekyll build --config _config.yml,_config.production.yml

# Deploy Message.

if [ $1 ]; then
  message=$1
else
  echo "Fetching last commit message for deploy message..."
  message=$(git log -1 --pretty=%B)
fi
echo "Using commit message:"
echo "$message"

# Preparing deploy repo.

if [ ! -d ../bowmemorialschool.github.io ]; then
  echo "No bowmemorial.github.io deploy repository found! Will clone adjacent to this directory..."
  pushd ..
  git clone git@github.com:bowmemorialschool/bowmemorialschool.github.io.git
  cd ./bowmemorialschool.github.io
  git checkout -b stage
else
  echo "Changing to ../bowmemorialschool.github.io directory..."
  pushd ../bowmemorialschool.github.io
fi

git checkout master
git pull
git branch -D stage
git checkout -b stage

popd

# Sync to deploy repo.

rsync -az --delete --exclude '.git' _site/ ../bowmemorialschool.github.io

# Deploy from deploy repo.

pushd ../bowmemorialschool.github.io
git add . 

git commit -a -m "$message"
git checkout master
git merge stage
git push -u origin master
git checkout stage

popd

# Rebuild the development site.

# ./tasks/jekyll
jekyll